CPPFLAGS= -Wall -Wextra -pedantic

all:
		# Insert command to compile the code and generate executable
		g++ -ldl sample.cpp -o sample
run:
	# Insert command to run the executable
		./sample.exe
checkmem:
	# Insert command to run the executable with valgrind

clean:
		# Insert command to clean object files, executables
		rm sample.exe
