CPPFLAGS= -Wall -Wextra -pedantic

all:
		# Insert command to compile the code and generate executable
		g++ -ldl test.cpp -o test
run:
	# Insert command to run the executable
		./test
checkmem:
	# Insert command to run the executable with valgrind

clean:
		# Insert command to clean object files, executables
		rm test
